### ISSUE TITLE
TalkGo算法之美提案2

### ISSUE THREAD

**Issue by JiaDuo-Lin** [talkgo/newspaper#14]
综合前面两期活动的经验，提交修改方案如下：

### 活动形式：
1. 以主题的形式进行举办，主题主要按题型进行选择，如二叉树，图，动态规划等。
2. 题目由负责人挑选，主要围绕该期的主题。 
3. 每个主题分为三个周期，每个周期一个星期。
4. 每周结束的时候都会有一次讨论会，对题目进行讨论总结。
5. 每次主题结束，也就是第四周，会举行一次比赛，主要是选择前三周的出现的题目（可能有改编），时长为一小时，主要看谁在最短时间内完成。 

### 参与方式
为期三周的主题活动可以免费报名参加。如果想参与讨论，以及第四周的比赛需要另行缴费。

### 费用说明
费用暂定：50元一个主题周期
每参与一次讨论会可以退还10块，即全部讨论参与退三十块
剩余部分主要用于第四次比赛，七成用于奖励比赛前三名（按四二一），两成用于奖励该次主题活动的负责人，一成留用于TalkGo算法之美的建设。

### 其他计划
- 将每一期内容整理到在线书本，形成自己的题库
- 构建属于TalkGo的OJ系统

**Comment by yangwenmai** [comment]
赞同，可以开始筹备运作了
