### ISSUE TITLE
关于网站运营建设的一些提案

### ISSUE THREAD

**Issue by songzhibin97** [talkgo/newspaper#5]
### 针对网站建设的一些模块划分

1.首先是我们的主版块（夜读分享板块）这个是我们的主打板块应该以夜读分享为核心去进行推广同时细分为夜读的全部录制视频、当期夜读的文字版本+分享ppt（此处需要大佬将视频内容精简出来）、以及短视频的剪辑（用自己的话导向技术模块）
2.和主版块相对应的新技术模块（这里的新技术特指但不限于大厂的框架、实用的第三方包、其他基于go编写框架社区的优值推文等）编辑成每日一报类似于`GoCN 每日新闻 https://gocn.vip/topics`
3.就是newspaper推得读书板块（读书的一些分享等等）
4.社区开启话题进行全员讨论（具体话题可以根据夜读、读书等发起）周期性关闭话题并选出优值评论归档发文
5.就是一些有名框架文档翻译或者特殊解读（我觉得这里还是区分一下的好，避免找的时候太繁琐与技术板块不冲突可以多个tag）

**Comment by yangwenmai** [comment]
可以跟另外一个提案一起？现在分开不同的提案，有一些难review和推进执行哦
