### ISSUE TITLE
网站的内容模块划分

### ISSUE THREAD

**Issue by YouEclipse** [talkgo/newspaper#6]
看了下改版前后的内容，加粗的部分是已有的内容，有些内容之间应该会有交叉
- **go夜读**
  - **视频回看**
  - **文字版**
- **读书会**
  - **读书笔记**
  - **好书推荐**
- **日常问答**
- go实战
  - 基础教程(暂无)
  - 设计模式(暂无)
  - web开发(暂无)
  - websocket 
  - **性能优化**  改版前的网站有部分内容
  - 案例分享(暂无)
  - 问题分析(暂无)
  - 基础设施(暂无)
    - ORM
    -  RPC框架
    -  Web框架
    -  API Gateway
  ...
- **Go招聘和面试**
   - **面试专题**
   - **招聘**
- **强烈推荐**
  - IDE相关(Vscode/Goland）实用插件
  - **官方、第三方库、工具链** 

- 知名Go项目相关
  - TiDB
  - NSQ
  - Docker
  ...
- 源码阅读(暂无)
  -  标准库
  -  开源库
  ...
- 云原生(暂无)
  - Kubernetes
  - Istio
  - MOSN 
- 翻译板块
  - **PaperReading** 已经有，感觉放这里挺合适的，好的论文可以翻译过来学习
  - Go官方Blog/Release log 
  - medium
  - reddit

**Comment by YouEclipse** [comment]
大致整理了一些，这样划分是否合理？或者还有啥补充的大家可以继续讨论.

**Comment by yangwenmai** [comment]
当前已有的论文阅读和问答、强烈推荐、招聘呢？

招聘只作为奖励，或者接受赞助。

**Comment by yangwenmai** [comment]
> 大致整理了一些，这样划分是否合理？或者还有啥补充的大家可以继续讨论.

你罗列和细分的已经很详细了。大家也可以再review一下，再一起提提建议，包括对内容本身怎么做也可以提意见。

**Comment by YouEclipse** [comment]
> 当前已有的论文阅读和问答、强烈推荐、招聘呢？
> 
> 招聘只作为奖励，或者接受赞助。

这些应该加上.

关于前面go夜读和读书会本身是我们自己产出的内容倒比较好做
go实战这块我觉得应该主力运营一下,前期可以转载一些现有的系列文章,比如煎鱼 飞雪大佬的系列文章,
后续可以内部发起一些写教程之类的计划,这些相对来说门槛低一些,做好文章的review,并且要定时产出.

云原生这块可以和云原生社区合作转载一些内容.

翻译的话是否可以成立一个翻译小组,每个月翻译几篇优秀的文章.

另外我还有个设想,关于奖励机制,是否可以定制一些go周边,比如贴纸,T恤之类的,这些成本相对低一些,但是会比较有意义.

**Comment by yangwenmai** [comment]
1. 我个人觉得纯粹的转载文章不太好，可以想其他的办法比较好。
>否则，全网都是相同的内容，没有太多价值，还不如来一个原创文章的解读？就像解读书一样。

2. 翻译组是可以考虑的。（主要需要找出处）

3. 云原生合作是有做过一期，更多可能性，可以再确定之后再做。

4. 奖励机制可以分配给 talkgo 周边小组来负责。

**Comment by YouEclipse** [comment]
看了下改版前后的内容，加粗的部分是已有的内容，有些内容之间应该会有交叉
- **go夜读**
  - **视频回看**
  - **文字版**
- **读书会**
  - **读书笔记**
  - **好书推荐**
- **日常问答**
- go实战
  - 基础教程(暂无)
  - 设计模式(暂无)
  - web开发(暂无)
  - **性能优化**  改版前的网站有部分内容
  - 案例分享(暂无)
  - 问题分析(暂无)
  - 基础设施(暂无)
    - ORM
    -  RPC框架
    -  Web框架
    -  API Gateway
  ...
- **Go招聘和面试**
   - **面试专题**
   - **招聘**
- **强烈推荐**
  - IDE相关(Vscode/Goland）实用插件
  - **官方、第三方库、工具链** 


- 知名Go项目相关
  - TiDB
  - NSQ
  - Docker
  ...
- 源码阅读(暂无)
  -  标准库
  -  开源库
  ...
- 云原生(暂无)
  - Kubernetes
  - Istio
  - MOSN 
- 翻译板块
  - **PaperReading** 已经有，感觉放这里挺合适的，好的论文可以翻译过来学习
  - Go官方Blog/Release log 
  - medium
  - reddit

**Comment by yangwenmai** [comment]
> 看了下改版前后的内容，加粗的部分是已有的内容，有些内容之间应该会有交叉
> 
> * **go夜读**
>   
>   * **视频回看**
>   * **文字版**
> * **读书会**
>   
>   * **读书笔记**
>   * **好书推荐**
> * **日常问答**
> * go实战
>   
>   * 基础教程(暂无)
>   * 设计模式(暂无)
>   * web开发(暂无)
>   * **性能优化**  改版前的网站有部分内容
>   * 案例分享(暂无)
>   * 问题分析(暂无)
>   * 基础设施(暂无)
>     
>     * ORM
>     * RPC框架
>     * Web框架
>     * API Gateway
>       ...
> * **Go招聘和面试**
>   
>   * **面试专题**
>   * **招聘**
> * **强烈推荐**
>   
>   * IDE相关(Vscode/Goland）实用插件
>   * **官方、第三方库、工具链**
> * 知名Go项目相关
>   
>   * TiDB
>   * NSQ
>   * Docker
>     ...
> * 源码阅读(暂无)
>   
>   * 标准库
>   * 开源库
>     ...
> * 云原生(暂无)
>   
>   * Kubernetes
>   * Istio
>   * MOSN
> * 翻译板块
>   
>   * **PaperReading** 已经有，感觉放这里挺合适的，好的论文可以翻译过来学习
>   * Go官方Blog/Release log
>   * medium
>   * reddit

你直接改主贴的内容吧？

**Comment by yangwenmai** [comment]
测试 GitHub Comment 是什么事件

**Comment by yangwenmai** [comment]
测试 GitHub Comment 是什么事件2
