### ISSUE TITLE
提案：TalkGo 算法之美

### ISSUE THREAD

**Issue by JiaDuo-Lin** [talkgo/newspaper#7]
## 特色

TalkGo 算法之美主要以各大互联网公司的面试题为主，帮助大家更了解一线大公司对算法题的要求，帮助大家“学以致用”。

## 活动形式

1. 以周期轮动形式举办。
2. 每个周期都需要单独报名。
3. 报名门槛： 50 元保证金。
4. 一次未按时打卡，扣 30 元，第二次将全部扣掉。
5. 扣除的保证金作为奖励金给组长和全勤同学。

### 筹备期

1. 确定刷题的主题
2. 刷题周期
3. 本期活动计划（划分的几个打卡时间和题解会议时间）
4. 招募组长和组员
5. 每次活动报名人员（包括组长）至少三人，所谓“三人行必有我师焉”。
6. 组委会收集保证金

### 启动和打卡期

1. 组长发布本期主题到 talkgo codeinterview 专栏
2. 组长发起启动会
3. 各自打卡，组长跟进小伙伴们的进度
4. 每次打卡结束点将会进行一次线上题解讨论会议（讲解解题思路，并对所有题解进行投票）
5. 主题结束后组长会输出一个简短的复盘和总结

注：组长可在平常招募小组组员成为组长，一同创建优质的刷题小组。

## 招募组长

1. 组长招募持续开放
2. 组长报名需要提供至少一个主题
3. 组长将被邀请加入 TalkGo codeinterview 组长群

## 奖惩机制

惩罚：

1. 一次未完成打卡，扣除保证金30元
2. 两次未完成打卡，保证金全部扣除

奖励：

1. 完成所有打卡后退还保证金
2. 获得被扣留的保证金的一部分
3. 组长获得被扣留保证金的50%

## 关于保证金

每次缴纳的保证金 50 元。
>保证金是为了保证活动的质量，以及对于参与人员的激励。

## 关于组长

1. 作为组长必须得以身作则的把题目刷好
2. 锻炼自己的组织能力，广交志同道合的朋友
3. 可以从每期的活动中获取的一定的现金奖励
4. 深度参与主题，对题目的总结将会更加深刻。

#### 主要职责与活动流程

1. 每次活动开始前确立好该期的活动主题和活动时长，并收集好题目
2. 报名担任当次活动的组长
3. 被确认组长后会被拉入talkgo刷题组的一个组长群，同时talkgo会帮忙开始征集成员
4. 成员集齐后，组长需要开一次启动会议，告诉成员活动的规则以及当期活动的一些时间安排。
5. 启动会议确认好每次给出题目的时间，以及每次答题和题解讨论会议的时间。
6. 组长需要按时将题目放到talkgo网站上，并通知成员答题。在下次给出题目之前需要开一次题解讨论会议，会议可以每一人讲解一下自己的答题思路，并且最终投票选一个大家认为比较好的题解出来。
7. 题解讨论会议时，组长确认成员是否完成一次打卡，并做好记录。
8. 最后一个题解讨论会议也是该期活动的总结会议，组长需要对本次活动进行总结。
9. 组长最后需要写一篇该期活动的总结文章，整理该期活动的题目和投票选出的比较好的题解，然后可以对该期活动的主题和题目总结为一篇文章，将会同步发到 talkgo网站和微信公众号。

**Comment by yangwenmai** [comment]
@Kydaa 提案通过，可以提个 PR 合入项目中

**Comment by halfrost** [comment]
去年我参加了几期暴力打卡营，进营就缴纳 300 元，要求每天都打卡，少打一天就扣 10 元，连续 3 天不打卡就踢出群，300 元也没收。到月底结算群里剩下来的人，按照打卡天数返还钱数。

看上面的活动描述，一周的打卡次数好像没有说明。可能意思是想让组长自己定？一周的时间我觉得稍微有点短了。因为有可能一周里面突然要忙几个需求，另外还有一点就是一周之内弄一个知识点，刷的题也许不够，掌握的时间可能稍微少了一些。按照专题来的话，我觉得 10 天比较合适。

以上只是我的一些建议，可以不用采纳😁，就是给你们参考参考其他人的做法。这个活动确实挺好的，希望你们能办起来啊。👍🏻

**Comment by JiaDuo-Lin** [comment]
您好：
谢谢你的建议，我会将你的建议发到内部组进行讨论。
其实前两期只是试验性运行，为的就是完善一些规则，所有有很多不足之处请你谅解，感谢您的建议。
打卡次数目前确实暂时由组长进行确定。时间也是有弹性的，也是有组长按照当期题量所决定，目前内部建议是一到两周。
2020.09.05


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "talkgo/newspaper"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月4日(星期五) 中午11:25
收件人:&nbsp;"talkgo/newspaper"<newspaper@noreply.github.com&gt;;
抄送:&nbsp;"林佳铎"<1043601529@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [talkgo/newspaper] 提案：TalkGo 算法之美 (#7)





 
去年我参加了几期暴力打卡营，进营就缴纳 300 元，要求每天都打卡，少打一天就扣 10 元，连续 3 天不打卡就踢出群，300 元也没收。到月底结算群里剩下来的人，按照打卡天数返还钱数。
 
看上面的活动描述，一周的打卡次数好像没有说明。可能意思是想让组长自己定？一周的时间我觉得稍微有点短了。因为有可能一周里面突然要忙几个需求，另外还有一点就是一周之内弄一个知识点，刷的题也许不够，掌握的时间可能稍微少了一些。按照专题来的话，我觉得 10 天比较合适。
 
以上只是我的一些建议，可以不用采纳😁，就是给你们参考参考其他人的做法。这个活动确实挺好的，希望你们能办起来啊。👍🏻
