### ISSUE TITLE
TalkGo 读书会第三期基本流程

### ISSUE THREAD

**Issue by yangwenmai** [talkgo/newspaper#8]
# TalkGo 读书会

TalkGo 读书会是由热爱学习，注重个人成长的一帮小伙伴们自由、自愿成立的虚拟线上组织。每个人都非常希望从「书📚」上学到知识，帮助自己实现成长和进步。

你是否还在暗自给自己下决心说：今年要读几本书，要学习什么什么而出现多次拖延和自己给自己不断的找借口呢？

如果你相信自己，相信 TalkGo 读书会，那赶紧加入我们吧，一起坚持，一起克服，一起成长。

>现在开始接受第三期报名，私聊我时请备注：TalkGo 读书会第三期，我的微信号：`mai_yang`。

## 活动周期

2个月

### 准备期
 
1. 读书组选出共读书籍，给出选择的理由；
2. 发起 TalkGo 读书会 X  期投票；
3. 确定后，由读书组制定本期读书计划表（可参考第一期、第二期读书计划表）；

### 启动期

1. 每期活动提前一~两周开放报名，由组织者收取保证金 100 元；
2. 报名人员必须参加启动会（一般是在正式启动的前一天晚上21点）；
3. 启动会上划分共读小组（1，2，3，4，5，6...以及静默独立小组）；

静默独立小组：

- 小组活动和启动会（强烈建议参加）可以不参加（不扣钱）
- 每周打卡还是要参加

#### 打卡

1. 打卡频次：小组每个成员每周至少打卡一次
2. 打卡形式：TalkGo 读书会专栏对应周的打卡帖上进行回帖打卡
3. 打卡验收：各小组组长负责验收和统计打卡情况（组委会抽查）

**何为打卡？**

对所读书籍做的心得体会和书本内容的批注，必须是自己组织出来的语言，摘录一律算作未打卡。

#### 小组研讨

1. 小组提前收集一些问题（延展内容）作为研讨话题
2. 每月一次线上讨论（辩论） 
3. 时长1~2小时（视情况而定
4. 每次评选最佳小组
5. 最佳小组负责当月研讨话题的整理和输出

#### 组长的职责与权益

**组长职责**：
1. 统计各组的日常打卡；
2. 把控小组打卡质量；
3. 组织小组每月研讨活动；
4. 推动小组成员的参与积极性；

**组长权益**：
1. 可参与当期优秀组长评选；
2. 免试获得参与 TalkGo 读书会志愿小组；
3. 小组所获奖励的优先享用（支配）权利；
4. 增强交际能力和管理能力；

#### 日常讨论

1. 志愿者推进大家在共读群内发出问题，引领讨论
2. 志愿者推进大家对优秀的日常讨论进行输出

### 奖惩制度

TalkGo 读书会退还保证金给各小组组长，再由组长根据实际情况进行退还保证金。

**奖励**：
1. 小组每周都全勤打卡，奖励一本书；
2. 每月的线上讨论表现最佳的组，奖励一本书；
3. 评选最优秀、最有价值的分享者2名，各奖励一本书；
4. 评选最佳组长，奖励一本书+私享一对一职业发展交流或等值的其他服务；

**惩罚**：
1. 未参与启动会扣50元；
2. 未打卡一次扣25元；
3. 小组缺席每月线上研讨会，小组成员每人扣25元；

## 推荐书

https://github.com/talkgo/night/issues/676

## 读书笔记

社区读书笔记方案详情: https://github.com/talkgo/newspaper/blob/master/readingnotes.md

[读书会第一期总结](https://talkgo.org/t/topic/628/)

**Comment by zsy619** [comment]
支持~~~督促一下自己

**Comment by LGTH** [comment]
点个赞，加油
